language: go
go_import_path: github.com/kevinburke/gobike

os: linux
dist: trusty
sudo: false

before_script:
  - go get ./...

script:
  - make race-test
  - make bench

go:
  - 1.11.x
  - 1.12.x
  - master

cache:
  directories:
    - $GOPATH/pkg
