[[constraint]]
  branch = "master"
  name = "github.com/golang/geo"

[[constraint]]
  name = "github.com/kevinburke/handlers"
  version = "0.39.0"

[[constraint]]
  name = "github.com/kevinburke/tss"
  version = "1.1"

[prune]
  go-tests = true
  unused-packages = true
